name: 🚀 Deploy on master

on:
  push:
    branches: [master]
jobs:
  build and deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: 🚚  Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.0.0"
      - name: create .env
        run: |
          touch .env
          echo REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }} >> .env
          echo REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} >> .env
      - name: 🎉 npm install and build
        run: |
          npm install
          CI=false npm run build
      - name: firebase-deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
